# config/vmware_cis_checks.yaml

checks:
  - id: no_1.2
    type: ntp
    name: Host must have reliable time synchronization sources
    CIS.NO: 2.6
    cmd: 'Get-VMHost | Select-Object Name, @{Name="NTPSetting"; Expression={ ($_ | Get-VMHostNtpServer)}}'

  - id: no_1.4
    type: advanced_setting
    name: Host must restrict inter-VM transparent page sharing (Automated)
    CIS.NO: 2.10
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Mem.ShareForceSalting | Select-Object Name, Value, Type, Description'

  - id: no_2.1
    type: service_tsm_ssh
    name: Host should deactivate SSH (Automated)
    CIS.NO: 3.1
    cmd: 'Get-VMHost | Get-VMHostService | Where { $_.key -eq "TSM-SSH" } | Select Key, Label, Policy, Running, Required'

  - id: no_2.2
    type: service_tsm
    name: Host must deactivate the ESXi shell (Automated)
    CIS.NO: 3.2
    cmd: 'Get-VMHost | Get-VMHostService | Where { $_.key -eq "TSM" } | Select Key, Label, Policy, Running, Required'

  - id: no_2.3
    type: advanced_setting
    name: Host must restrict inter-VM transparent page sharing (Automated)
    CIS.NO: 2.10
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Mem.ShareForceSalting | Select-Object Name, Value, Type, Description'

  - id: no_2.4
    type: snmp_manual
    name: Host should deactivate SNMP (Manual)
    CIS.NO: 3.6
    cmd: 'None'

  - id: no_2.5
    type: dcui_timeout
    name: Host must automatically terminate idle DCUI sessions (Automated)
    CIS.NO: 3.7
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name UserVars.DcuiTimeOut'

  - id: no_2.6
    type: shell_warning_manual
    name: Host must not suppress warnings that the shell is enabled (Manual)
    CIS.NO: 3.10
    cmd: 'None'

  - id: no_2.7
    type: password_complexity_manual
    name: Host must enforce password complexity (Manual)
    CIS.NO: 3.11
    cmd: 'Get-VMHost | Get-VMHostService | Where { $_.key -eq "TSM-SSH" } | Select VMHost, Key, Label, Policy, Running, Required'

  - id: no_2.8
    type: account_lock_failure
    name: Host must lock an account after a specified number of failed login attempts (Automated)
    CIS.NO: 3.12
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Security.AccountLockFailure'

  - id: no_2.9
    type: account_unlock_time
    name: Host must unlock accounts after a specified timeout period (Automated)
    CIS.NO: 3.13
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Security.AccountUnlockTime'

  - id: no_2.10
    type: password_history_manual
    name: Host must configure the password history setting to restrict the reuse of passwords (Manual)
    CIS.NO: 3.14
    cmd: 'Get-VMHost | Get-AdvancedSetting Security.PasswordHistory'

  - id: no_2.11
    type: password_max_days_manual
    name: Host must be configured with an appropriate maximum password age (Manual)
    CIS.NO: 3.15
    cmd: 'Get-VMHost | Get-AdvancedSetting Security.PasswordMaxDays'

  - id: no_2.12
    type: session_timeout_api_manual
    name: Host must configure a session timeout for the API (Manual)
    CIS.NO: 3.16
    cmd: 'None'

  - id: no_2.13
    type: idle_host_client_manual
    name: Host must automatically terminate idle host client sessions (Manual)
    CIS.NO: 3.17
    cmd: 'None'

  - id: no_2.14
    type: dcui_access_manual
    name: Host must have an accurate DCUI.Access list (Manual)
    CIS.NO: 3.18
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name DCUI.Access'

  - id: no_2.15
    type: exception_users_manual
    name: Host must have an accurate Exception Users list (Manual)
    CIS.NO: 3.19
    cmd: 'None'

  - id: no_2.16
    type: tls_version_manual
    name: Host must enable the highest version of TLS supported (Manual)
    CIS.NO: 3.26
    cmd: 'None'

  - id: no_3.1
    type: syslog_persistent_manual
    name: Host must configure a persistent log location for all locally stored system logs (Manual)
    CIS.NO: 4.1
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Syslog.global.logDir'

  - id: no_3.2
    type: advanced_setting
    name: Host must transmit system logs to a remote log collector (Automated)
    CIS.NO: 4.2
    cmd: 'Get-VMHost | Get-AdvancedSetting -Name Syslog.global.logHost'

  - id: no_3.3
    type: syslog_info_level_manual
    name: Host must set the logging informational level to info (Manual)
    CIS.NO: 4.4
    cmd: 'None'

  - id: no_3.4
    type: log_filtering_manual
    name: Host must deactivate log filtering (Manual)
    CIS.NO: 4.5
    cmd: 'None'

  - id: no_3.5
    type: tls_log_verify_manual
    name: Host must verify certificates for TLS remote logging endpoints (Manual)
    CIS.NO: 4.10
    cmd: 'None'


