# config/vmware_cis_checks.yaml
checks:
  - id: no_1.2
    type: ntp
  - id: no_1.4
    type: advanced_setting
  - id: no_2.1
    type: service_tsm_ssh
  - id: no_2.2
    type: service_tsm
  - id: no_2.3
    type: advanced_setting


